### PR TITLE
Update dependencies + make linter pass

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
## Proposed Changes
I updated the dependencies because it fixes some bugs related to incompatible versions of `posthtml`.

## Types of Changes
- [x] Bug (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature which changes existing functionality)

## Checklist
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) guide
- [x] Lint and unit tests pass with my changes *(required the deletion of a single empty line)*
- [x] I have added tests that prove my fix is effective/works *(I can't add tests for updates, but everything still works)*
- [x] I have added necessary documentation (if appropriate) *(it's not)*
- [ ] Any dependent changes are merged and published in downstream modules *(no idea what this means)*

## Further Comments
I don't really see a reason why this shouldn't be merged, it's just a routine update.

### CODE REVIEW

**Comment by HoldYourWaffle** [comment]
I'll probably create one or two more PR's, so if you decide to merge this you should probably wait for those before you release a new version.

**Comment by HoldYourWaffle** [comment]
Oh apparently one of the upstream updates broke compatibility with Node v4. Unfortunately there's probably nothing we can do about that, and I don't think it should be a problem nowadays.

**Comment by Scrum** [comment]
@HoldYourWaffle Hi, you can reset support for old node

**Comment by HoldYourWaffle** [comment]
@Scrum I'm not sure what you mean, do you want me to remove the travis entry or somehow keep support for Node 4?

**Comment by Scrum** [comment]
@HoldYourWaffle 
> do you want me to remove the travis entry or somehow keep support for Node 4?

Yep, and package.json

https://github.com/posthtml/express-posthtml/blob/048f2d3f2dcb4dd08c2eb0b36f5e7c0e911eab75/package.json#L5-L7

**Comment by HoldYourWaffle** [comment]
@Scrum fixed it

**Comment by Scrum** [comment]
@HoldYourWaffle thank you very much!

**Pull request merged**
